<?PHP

/**
*
* @mod package		Download Mod 6
* @file				dl_help.php 24 2014/10/08 OXPUS
* @copyright		(c) 2005 oxpus (Karsten Ude) <webmaster@oxpus.de> http://www.oxpus.de
* @copyright mod	(c) hotschi / demolition fabi / oxpus
* @license			http://opensource.org/licenses/gpl-license.php GNU Public License
*
*/

/*
* [French] language file for Download MOD 6
*/

/**
* DO NOT CHANGE
*/
if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

$lang = array_merge($lang, array(
	'HELP_TITLE' => 'Aide en ligne du Download MOD',

	'DL_NO_HELP_AVIABLE' => 'Aucune aide n\'est disponible pour cette option',

	'HELP_DL_ACTIVE'			=> 'Active ou désactive les téléchargements selon les options suivantes.',
	'HELP_DL_ANTISPAM'			=> 'Cette option bloque les téléchargements pour lesquels l\'utilisateur doit, en plus du trafic requis, avoir un nombre minimal de messages publiés et avoir posté ce nombre de messages au cours des dernières heures.<br /><br />Exemple :<br />Les paramètres indiquent 25 messages en 24 heures.<br />Sur la base de ces paramètres, les téléchargements seront bloqués pour l\'utilisateur s\'il/elle a posté 25 messages ou plus au cours des 24 dernières heures.<br />Cette option vise à prévenir le spam concernant les téléchargements, en particulier pour les nouveaux utilisateurs, avant qu\'un membre de l\'équipe n\'en prenne connaissance et n\'agisse.<br />Le téléchargement sera toujours affiché comme disponible pour inciter l\'utilisateur. L\'utilisateur recevra seulement un message indiquant l\'absence d\'autorisations.<br /><br />Pour désactiver cette vérification, réglez une ou les deux valeurs sur 0.',
	'HELP_DL_APPROVE'			=> 'Cela approuvera immédiatement le téléchargement si vous soumettez ce formulaire.<br />En revanche, ce téléchargement sera masqué pour les utilisateurs.',
	'HELP_DL_APPROVE_COMMENTS'	=> 'Si vous désactivez cette option, chaque nouveau commentaire devra être approuvé par un modérateur ou un administrateur des téléchargements avant d\'être visible par les autres utilisateurs.',

	'HELP_DL_BUG_TRACKER_CAT'	=> 'Active le suivi des bugs pour les téléchargements de cette catégorie.<br />Les bugs peuvent être postés et consultés par tout utilisateur enregistré pour les téléchargements concernés et pour d\'autres catégories si le suivi des bugs y est également activé.<br />Seuls les administrateurs et les modérateurs du forum peuvent gérer les bugs.<br />Pour chaque modification d\'un message de bug, l\'auteur recevra un e‑mail, et le membre de l\'équipe chargé du bug sera également informé.',

	'HELP_DL_CAT_DESCRIPTION'	=> 'Une courte description pour cette catégorie.<br />Les BBCodes ne sont pas disponibles ici.<br />Cette description sera affichée sur l\'index des téléchargements et sur les sous‑catégories.',
	'HELP_DL_CAT_EDIT_LINK'		=> 'Détermine qui peut voir et utiliser le lien d\'édition d\'un téléchargement depuis la vue de la catégorie, si cette option n\'est pas désactivée.<br />"Téléchargements propres" n\'est actif que si l\'option d\'éditer ses propres téléchargements est également activée.',
	'HELP_DL_CAT_ICON'			=> 'L\'icône de catégorie doit déjà être téléchargée dans le forum, par ex. dans le dossier /images/dl_icons/ (le dossier doit exister avant de pouvoir y téléverser des icônes).<br />Entrez l\'URL relative depuis la racine du forum, p. ex. images/dl_icon.gif.<br /><br />Veuillez n\'utiliser que des icônes affichables par un navigateur web.<br />Recommandé : JPG, GIF ou PNG.<br />Tenez compte de la taille des images pour éviter de déformer l\'index des téléchargements, car les icônes ne seront pas redimensionnées automatiquement.',
	'HELP_DL_CAT_NAME'			=> 'Nom de la catégorie tel qu\'il sera affiché partout.<br />Évitez les caractères spéciaux pour éviter des entrées confuses dans le jumpbox.',
	'HELP_DL_CAT_PARENT'		=> 'Le niveau principal ou une autre catégorie à laquelle cette catégorie peut être rattachée.<br />Avec ce menu déroulant dynamique, vous pouvez construire une structure hiérarchique pour vos téléchargements.',
	'HELP_DL_CAT_PATH'			=> 'Ici vous devez entrer un chemin existant vers vos téléchargements.<br />Cette valeur doit être le nom d\'un sous‑dossier sous le dossier principal (p. ex. downloads/) que vous avez défini dans la configuration principale.<br />Entrez le nom du dossier avec une barre oblique à la fin.<br />Par exemple, s\'il existe le dossier "downloads/mods/" vous devez entrer "mods/".<br />Lorsque vous soumettez ce formulaire, le dossier sera vérifié.<br />Assurez‑vous que le sous‑dossier existe réellement !<br />Si le dossier est un sous‑dossier d\'un autre sous‑dossier, entrez la hiérarchie complète ici.<br />Ex. "downloads/mods/misc/" doit être entré comme "mods/misc/".<br />Assurez‑vous que chaque sous‑dossier possède les permissions CHMOD 777 et faites attention à la casse sur Unix/Linux.',
	'HELP_DL_CAT_RULES'			=> 'Ces règles seront affichées au-dessus des sous‑catégories et téléchargements lors de la consultation de la catégorie.',
	'HELP_DL_CAT_TRAFFIC'		=> 'Indiquez le trafic mensuel maximum pour cette catégorie.<br />Ce trafic n\'augmente pas le trafic global !<br />Entrez 0 pour désactiver la limite.',
	'HELP_DL_CHOOSE_CATEGORY'	=> 'Choisissez la catégorie qui contiendra ce téléchargement.<br />Le fichier doit déjà être enregistré dans le dossier que vous avez indiqué dans la gestion des catégories avant d\'enregistrer ce téléchargement.<br />Sinon, vous obtiendrez un message d\'erreur.',
	'HELP_DL_COMMENTS'			=> 'Activez le système de commentaires pour cette catégorie.<br />Les utilisateurs que vous autorisez avec les menus déroulants pourront voir et/ou poster des commentaires dans cette catégorie.<br />Les administrateurs et modérateurs des téléchargements peuvent éditer et supprimer tous les commentaires, les auteurs peuvent gérer leurs propres textes.',
	'HELP_DL_COPY_PERMISSIONS'	=> 'Copie les permissions depuis la catégorie sélectionnée.<br />Si vous avez sélectionné la catégorie parente, cette catégorie héritera des permissions de la catégorie sous laquelle elle est rattachée.<br />Si la catégorie parente est l\'index des téléchargements, cette catégorie n\'hérite d\'aucune permission. Dans ce cas, choisissez une autre catégorie ou définissez les permissions via le module Permissions.',

	'HELP_DL_DELAY_AUTO_TRAFFIC'	=> 'Indiquez ici le nombre de jours avant qu\'un nouvel utilisateur reçoive le premier trafic automatique.<br />Le délai commence à la date d\'inscription.<br />Entrez 0 pour désactiver ce délai.',
	'HELP_DL_DELAY_POST_TRAFFIC'	=> 'Indiquez ici le nombre de jours après lequel un nouvel utilisateur recevra le premier trafic lié aux publications.<br />Le délai commence à la date d\'inscription.<br />Entrez 0 pour désactiver ce délai.',
	'HELP_DL_DISABLE_EMAIL'			=> 'Avec cette option vous pouvez activer ou désactiver complètement les notifications par e‑mail concernant les téléchargements ajoutés ou modifiés.<br />Lorsque cette fonction est activée ici, elle peut être désactivée individuellement lors de l\'ajout ou de la modification d\'un téléchargement.<br />Seuls les utilisateurs ayant activé les notifications par e‑mail pour les nouveaux ou modifiés téléchargements dans leur configuration de téléchargements recevront un e‑mail.<br />Ils peuvent accéder à leur configuration depuis le pied de page des téléchargements.',
	'HELP_DL_DISABLE_EMAIL_FILES'	=> 'Cochez cette option pour supprimer la notification par e‑mail.<br />Cela n\'affectera pas la notification popup/message sur le forum ni la mise à jour de l\'heure de dernière modification.',
	'HELP_DL_DISABLE_POPUP'			=> 'Avec cette option vous pouvez activer ou désactiver complètement les notifications popup ou les messages sur le forum concernant les nouveaux téléchargements ou modifications.<br />Lorsque cette fonction est activée ici, elle peut être désactivée individuellement lors de l\'ajout ou de la modification d\'un téléchargement.<br />Seuls les utilisateurs ayant activé les notifications popup pour les nouveaux ou modifiés téléchargements dans leur configuration recevront une popup/message sur le forum.<br />Ils peuvent accéder à leur configuration depuis le pied de page des téléchargements.',
	'HELP_DL_DISABLE_POPUP_FILES'	=> 'Cochez cette option pour supprimer la notification popup/message sur le forum.<br />Cela n\'affectera pas les notifications par e‑mail ni la mise à jour de l\'heure de dernière modification.',
	'HELP_DL_DISABLE_POPUP_NOTIFY'	=> 'Si cette option est activée, vous pouvez empêcher la mise à jour de l\'heure de modification lors de l\'édition d\'un téléchargement.',
	'HELP_DL_DROP_TRAFFIC_POSTDEL'	=> 'Si un message ou un sujet est supprimé, cette option peut diminuer également le trafic de l\'auteur (pour la suppression d\'un sujet seul l\'auteur du sujet est pris en compte).<br />Notez que l\'utilisateur peut obtenir un autre montant de trafic en postant que celui qu\'il perd en supprimant son message/sujet, donc les montants attribués pour la publication et la suppression peuvent différer.',

	'HELP_DL_EDIT_OWN_DOWNLOADS'	=> 'Si vous activez cette option, chaque utilisateur pourra modifier ses propres fichiers téléversés sans être administrateur ou modérateur des téléchargements.',
	'HELP_DL_EDIT_TIME'				=> 'Indiquez ici le nombre de jours pendant lesquels un téléchargement modifié sera marqué.<br />Entrez 0 pour désactiver cette fonction.',
	'HELP_DL_ENABLE_JUMPBOX'		=> 'Cette option affiche ou masque le jumpbox dans le pied de page des téléchargements.<br />Si le jumpbox est désactivé, cela peut améliorer les performances du panneau de téléchargements.',
	'HELP_DL_ENABLE_POST_TRAFFIC'	=> 'Définissez la quantité de trafic qu\'un utilisateur recevra pour la création de sujets, réponses ou citations selon les options suivantes.',
	'HELP_DL_ENABLE_RATE'			=> 'Avec cette option vous pouvez activer/désactiver le système de notation.<br />Si des notes existent déjà, elles ne seront pas supprimées et le mod les affichera dès que vous réactivez le système de notation.',
	'HELP_DL_ENABLE_TOPIC'			=> 'Permet de créer un sujet pour chaque nouveau téléchargement ajouté via le panneau d\'administration dans le forum indiqué et avec le texte fourni. Pour les téléchargements nécessitant une approbation, le sujet sera créé via le panneau de modération.',
	'HELP_DL_EXT_NEW_WINDOW'		=> 'Ouvre les téléchargements externes dans une nouvelle fenêtre du navigateur ou dans la fenêtre actuelle.',
	'HELP_DL_EXTERN'				=> 'Activez cette fonction pour des fichiers externes dont vous saisirez l\'URL dans le champ ci‑dessus (http://www.example.com/media.mp3).<br />La fonction "free" devient alors sans effet.<br />Optionnellement, vous pouvez entrer la taille du fichier pour le téléchargement externe. Cette taille sera affichée partout.<br />Notez que pour les téléchargements internes, la taille affichée sera la taille réelle ; dans ce cas, les modifications de cette valeur seront ignorées et remplacées par la taille réelle du fichier.',
	'HELP_DL_EXTERN_UP'				=> 'Activez cette fonction pour des fichiers externes dont vous saisirez l\'URL dans le champ de droite (http://www.example.com/media.mp3). La fonction "free" devient alors sans effet.',

	'HELP_DL_FILE_DESCRIPTION'	=> 'Une courte description pour ce téléchargement.<br />Elle sera affichée dans la catégorie. Les BBCodes sont désactivés pour ce texte.<br />Veuillez entrer uniquement un court texte afin de réduire la charge lors de l\'ouverture de la catégorie.',
	'HELP_DL_FILE_HASH_ALGO'	=> 'Définit la méthode utilisée pour calculer la somme de contrôle (hash) pour chaque téléchargement.<br />Le hash sera calculé pour tous les téléchargements et variantes existants, mais ne sera affiché dans les détails que si les options appropriées sont activées.<br />Vous pouvez utiliser md5 ou sha1, méthodes généralement disponibles sur les serveurs.<br />Le mod calculera automatiquement le hash à l\'ajout ou la modification d\'un téléchargement. Le hash sera également calculé lors de l\'ouverture de la vue détaillée si le hash n\'a pas été calculé et enregistré auparavant (utile après une mise à jour du mod ou un changement de méthode).<br /><br />Remarque :<br />Si la méthode de hash est modifiée, toutes les valeurs de hash existantes seront supprimées car elles ne correspondent pas à la nouvelle méthode.',
	'HELP_DL_FILES_URL'			=> 'Le nom du fichier pour ce téléchargement.<br />Entrez ce nom sans chemin initial ni slash.<br />Le fichier doit exister avant d\'enregistrer ce téléchargement sinon vous obtiendrez une erreur.<br />Remarque : extensions de fichiers interdites : tout fichier avec une extension interdite sera bloqué.',

	'HELP_DL_GUEST_STATS_SHOW'	=> 'Cette option inclut ou exclut les données statistiques des invités dans les statistiques publiques de la catégorie.<br />Le script continuera à collecter toutes les données.<br />L\'outil de statistiques de l\'ACP affiche toujours l\'ensemble complet des données.',

	'HELP_DL_HACK_AUTOR'			=> 'L\'auteur de ce fichier de téléchargement.<br />Laissez vide pour masquer cette valeur dans les détails du téléchargement et dans la vue d\'ensemble.',
	'HELP_DL_HACK_AUTOR_EMAIL'		=> 'L\'adresse e‑mail de l\'auteur.<br />Si vous ne la saisissez pas, elle sera masquée dans les détails du téléchargement et dans la vue d\'ensemble.',
	'HELP_DL_HACK_AUTOR_WEBSITE'	=> 'Site web de l\'auteur.<br />Cette URL devrait être le site de l\'auteur, pas forcément la page du téléchargement.<br />Veuillez ne pas entrer de liens vers des sites protégés ou douteux.',
	'HELP_DL_HACK_DL_URL'			=> 'La page pointant vers un téléchargement alternatif pour ce fichier.<br />Cela peut être le site de l\'auteur ou un autre site alternatif.<br />Veuillez ne pas entrer de lien de téléchargement direct si l\'auteur ne l\'autorise pas.',
	'HELP_DL_HACK_VERSION'			=> 'Indication de la version de la release du téléchargement.<br />Cela sera toujours affiché à côté du téléchargement.',
	'HELP_DL_HACKLIST'				=> 'Avec cette option, vous pouvez ajouter ce téléchargement à la hacklist (doit être activée dans la configuration principale) en choisissant Oui.<br />Non n\'insérera pas le téléchargement dans la hacklist.<br />L\'affichage d\'informations supplémentaires ne s\'affichera que dans les détails du téléchargement.',
	'HELP_DL_HOTLINK_ACTION'		=> 'Choisissez ici comment le script doit réagir lorsqu\'il empêche un lien direct vers un téléchargement (voir également l\'option suivante).<br />Il peut afficher un message (réduit la charge serveur) ou rediriger vers le téléchargement (génère du trafic).',

	'HELP_DL_ICON_FREE_FOR_REG'	=> 'Cette option bascule l\'icône blanche pour les téléchargements gratuits pour les utilisateurs enregistrés afin que les invités voient également l\'icône blanche.<br />Si vous désactivez cette option, les invités verront l\'icône rouge à la place.',
	'HELP_DL_IS_FREE'			=> 'Activez cette fonction si le téléchargement doit être gratuit pour tout le monde.<br />Les comptes de trafic ne seront pas utilisés.<br />Choisissez "free for reg. Users" pour autoriser le téléchargement gratuit uniquement aux utilisateurs enregistrés.',

	'HELP_DL_KLICKS_RESET'		=> 'Cette option peut remettre le compteur de clics de ce mois à zéro.<br />Utile pour réinitialiser le suivi après la mise à jour d\'une release.',

	'HELP_DL_LATEST_COMMENTS'		=> 'Cette option affiche les X derniers commentaires dans les détails du téléchargement. Entrez 0 pour désactiver ce bloc.',
	'HELP_DL_LIMIT_DESC_ON_INDEX'	=> 'Coupe les descriptions après le nombre de caractères saisi.<br />Mettez 0 pour désactiver cette fonction.',
	'HELP_DL_LINKS_PER_PAGE'		=> 'Cette option contrôle combien de téléchargements sont affichés par page de catégorie et dans les statistiques ACP.<br />Dans la hacklist et la liste d\'aperçu, la valeur "topics per page" du forum sera utilisée.',

	'HELP_DL_METHOD'			=> 'La méthode "ancienne" envoie le fichier directement au client web.<br />Cette méthode est compatible avec la plupart des environnements web, mais n\'affiche pas la taille réelle du fichier pendant le téléchargement, l\'utilisateur ne peut donc pas estimer le temps restant.<br />La méthode "nouvelle" affiche la taille réelle mais peut engendrer des erreurs.<br />Utilisez la méthode "ancienne" si vous rencontrez des problèmes avec la nouvelle.<br />Si rien ne fonctionne, cochez "direct" pour lier directement au fichier sur le serveur si la lecture via PHP dépasse la limite mémoire.',
	'HELP_DL_METHOD_QUOTA'		=> 'Définissez ici la taille à partir de laquelle le fichier sera lu en mode chunked lorsque vous avez choisi la méthode "nouvelle".<br />Sous ce quota, le fichier sera récupéré par readfile() et envoyé directement au client web.',
	'HELP_DL_MOD_DESC'			=> 'Descriptions détaillées du MOD saisi.<br />Vous pouvez utiliser BBCodes et smileys dans ce texte.<br />Les sauts de ligne seront formatés.<br />Ce texte s\'affiche uniquement dans les détails du téléchargement.',
	'HELP_DL_MOD_DESC_ALLOW'	=> 'Active le bloc d\'informations sur le MOD lors de l\'ajout ou la modification d\'un téléchargement.',
	'HELP_DL_MOD_LIST'			=> 'Active ce bloc dans les détails du téléchargement.<br />Si vous ne l\'activez pas, le bloc complet ne sera pas affiché.',
	'HELP_DL_MOD_REQUIRE'		=> 'Indique les autres MODs nécessaires pour installer ou utiliser ce téléchargement.<br />Ce texte s\'affiche uniquement dans les détails du téléchargement.',
	'HELP_DL_MOD_TEST'			=> 'Indique sur quelle version de phpBB ce MOD a été testé avec succès.<br />Entrez simplement la version du forum test (ex : X pour phpBB X).<br />Ce texte s\'affiche uniquement dans les détails du téléchargement.',
	'HELP_DL_MOD_TODO'			=> 'Ici vous pouvez entrer les prochaines étapes prévues pour ce MOD ou celles en cours.<br />Cela crée la liste de tâches (ToDo) accessible depuis le pied de page des téléchargements.<br />Le texte informe les utilisateurs du statut actuel du MOD.<br />Les sauts de ligne seront formatés, les BBCodes ne sont pas disponibles ici.',
	'HELP_DL_MOD_WARNING'		=> 'Conseils importants concernant ce MOD à prendre en compte lors de l\'installation ou de l\'interaction avec d\'autres MODs.<br />Ce texte s\'affiche dans les détails du téléchargement avec une mise en évidence (par défaut en rouge).<br />Les sauts de ligne seront formatés. Les BBCodes ne sont pas disponibles.',
	'HELP_DL_MUST_APPROVE'		=> 'Activez cette option pour approuver chaque nouveau fichier uploadé avant qu\'il ne soit affiché dans la catégorie.<br />Les administrateurs et modérateurs des téléchargements recevront des e‑mails pour chaque nouveau téléchargement non approuvé.',

	'HELP_DL_NAME'					=> 'Nom du téléchargement tel qu\'il sera affiché à différents endroits.<br />Évitez les caractères spéciaux pour réduire les erreurs d\'affichage.',
	'HELP_DL_NEW_TIME'				=> 'Indiquez le nombre de jours pendant lesquels un téléchargement sera marqué comme "nouveau".<br />Entrez 0 pour désactiver cette fonction.',
	'HELP_DL_NEWTOPIC_TRAFFIC'		=> 'Pour chaque nouveau sujet posté, l\'auteur recevra le trafic indiqué en complément de son trafic actuel.',
	'HELP_DL_NO_CHANGE_EDIT_TIME'	=> 'Cochez cette option pour empêcher la mise à jour de l\'heure de la dernière modification pour ce téléchargement.<br />Cela n\'affectera pas les notifications par e‑mail ou popup/message sur le forum.',

	'HELP_DL_OFF_HIDE'					=> 'Masque le lien dans la navigation du forum.<br />Sinon, la zone de téléchargement n\'affichera qu\'un message.',
	'HELP_DL_OFF_NOW_TIME'				=> 'Désactive immédiatement les téléchargements ou désactive automatiquement les téléchargements entre les plages horaires suivantes.',
	'HELP_DL_OFF_PERIOD'				=> 'Période pendant laquelle le téléchargement sera automatiquement désactivé.',
	'HELP_DL_OFF_PERIOD_TILL'			=> 'Période pendant laquelle le téléchargement sera automatiquement désactivé.',
	'HELP_DL_ON_ADMINS'					=> 'Permet aux administrateurs du forum d\'accéder aux téléchargements et de travailler même si le mod téléchargement est désactivé.<br />Sinon, les administrateurs seront également verrouillés.',
	'HELP_DL_OVERALL_TRAFFIC'			=> 'Limite globale pour les utilisateurs enregistrés pour tous les téléchargements et, si activé, pour les uploads, qui ne peut être dépassée dans le mois en cours.<br />Après atteinte de cette limite, chaque téléchargement sera marqué et verrouillé et, si activé, les uploads seront impossibles.',
	'HELP_DL_OVERALL_GUEST_TRAFFIC'		=> 'Limite globale pour les invités pour tous les téléchargements (et uploads si activé) qui ne peut être dépassée dans le mois en cours.<br />Après atteinte de cette limite, chaque téléchargement sera marqué et verrouillé et, si activé, les uploads seront impossibles.',
	'HELP_DL_OVERVIEW_LINK'				=> 'Affiche ou masque le lien vers la liste globale.<br />Remarque : si le lien est désactivé, la liste globale ne peut pas être ouverte via un lien direct !',

	'HELP_DL_PHYSICAL_QUOTA'	=> 'Limite physique globale que le MOD peut utiliser pour stocker et gérer les téléchargements.<br />Si cette limite est atteinte, de nouveaux téléchargements ne pourront être ajoutés que s\'ils sont uploadés via FTP et ajoutés via la gestion des fichiers dans l\'ACP.',
	'HELP_DL_POSTS'				=> 'Chaque utilisateur, y compris les administrateurs et modérateurs des téléchargements, doit avoir publié au minimum ce nombre de messages pour pouvoir télécharger les fichiers non gratuits.<br />Il est recommandé d\'installer un MOD anti‑spam pour éviter les posteurs spammeurs.<br />Entrez 0 pour désactiver cette fonction (recommandé pour les forums jeunes).',
	'HELP_DL_PREVENT_HOTLINK'	=> 'Activez cette option si vous souhaitez empêcher tout lien direct vers un téléchargement en dehors de la page de détail du téléchargement.<br />Cette option ne constitue PAS une protection de dossier !',

	'HELP_DL_RATE_POINTS'			=> 'Définit le nombre maximal de points de notation qu\'un utilisateur peut attribuer à un téléchargement.<br /><br /><strong>Remarque :</strong><br />Si vous modifiez ces paramètres, tous les points de notation existants seront réinitialisés afin que le mod puisse recalculer correctement les notes !',
	'HELP_DL_REPLY_TRAFFIC'			=> 'L\'utilisateur recevra le trafic indiqué pour chaque nouvelle réponse ou citation en complément de son trafic.',
	'HELP_DL_REPORT_BROKEN'			=> 'Active ou désactive la fonction de signalement des téléchargements cassés.<br />Si vous choisissez "pas pour les invités", seuls les utilisateurs enregistrés pourront signaler les téléchargements.',
	'HELP_DL_REPORT_BROKEN_LOCK'	=> 'Si vous activez cette option, le téléchargement sera verrouillé lorsqu\'il est signalé comme cassé.<br />Le bouton de téléchargement sera masqué et aucun utilisateur ne pourra télécharger le fichier tant qu\'un administrateur ou un modérateur n\'aura pas débloqué le téléchargement.',
	'HELP_DL_REPORT_BROKEN_MESSAGE'	=> 'Si un téléchargement est signalé comme cassé, un message à ce sujet sera affiché.<br />Si vous activez cette option, le message n\'apparaîtra que lorsque le téléchargement est verrouillé.',
	'HELP_DL_REPORT_BROKEN_VC'		=> 'Active une confirmation visuelle (captcha) lorsqu\'un utilisateur signale un téléchargement cassé.<br />Le signalement sera enregistré uniquement si le code saisi est correct et les administrateurs/modérateurs recevront un e‑mail.',

	'HELP_DL_RSS_ENABLE'				=> 'Le flux RSS pour les téléchargements peut être activé/désactivé entièrement.<br />Lorsque cette fonction est désactivée, les deux options suivantes définissent ce que l\'utilisateur voit à la place.',
	'HELP_DL_RSS_OFF_ACTION'			=> 'Cette option définit le comportement du flux lorsque celui‑ci est désactivé.',
	'HELP_DL_RSS_OFF_TEXT'				=> 'Ce message sera affiché dans le flux RSS à la place des entrées de téléchargement si la fonction est désactivée et que l\'option correspondante est réglée pour afficher le texte.<br />Si l\'option est de rediriger, le texte restera défini mais ne sera pas affiché.',
	'HELP_DL_RSS_CATS'					=> 'Les entrées du flux RSS seront prises de toutes les catégories ou des catégories sélectionnées listées ici.<br />Pour sélectionner plusieurs catégories, maintenez la touche CTRL enfoncée pendant la sélection.<br />Vous pouvez choisir d\'inclure ou d\'exclure les catégories sélectionnées dans le flux.',
	'HELP_DL_RSS_PERMS'					=> 'En complément de la sélection des catégories, il peut être utile de prendre en compte les permissions des utilisateurs dans les catégories pour éviter d\'afficher des téléchargements non autorisés à l\'utilisateur courant (invités/bots).<br />L\'option "pour les invités" sélectionne uniquement les catégories visibles par les invités et bots.<br />Si aucun élément ne correspond pour l\'utilisateur ou l\'invité/bot, le script se comporte comme si le flux était désactivé.',
	'HELP_DL_RSS_NEW_UPDATE'			=> 'Affiche les marques pour les téléchargements nouveaux ou mis à jour comme l\'icône mini dans la vue catégorie.',
	'HELP_DL_RSS_NUMBER'				=> 'Nombre maximal de téléchargements affichés dans le flux.',
	'HELP_DL_RSS_SELECT'				=> 'Cette option définit si le titre affiché dans le flux est le dernier ou un titre aléatoire, en se basant sur les catégories sélectionnées, les permissions et le nombre maximum.',
	'HELP_DL_RSS_DESC_LENGTH'			=> 'Avec cette option, les descriptions des téléchargements peuvent être affichées. Vous pouvez choisir la description complète ou la courte (comme sur l\'index).<br /><br /><strong>Attention :</strong><br />Tous les lecteurs RSS ne gèrent pas le HTML de la même façon ; la description peut s\'afficher incorrectement ou l\'entrée peut ne pas s\'afficher. Dans ce cas, l\'utilisateur doit utiliser un autre lecteur ou vous devez désactiver les descriptions.',
	'HELP_DL_RSS_DESC_LENGTH_SHORTEN'	=> 'Coupe la description des téléchargements après le nombre de caractères défini ici si l\'option précédente est réglée pour afficher une description raccourcie.<br />0 masque la description.',

	'HELP_DL_SHORTEN_EXTERN_LINKS'	=> 'Indiquez la longueur d\'affichage des liens externes dans les détails du téléchargement.<br />Selon la longueur, le lien sera coupé au milieu ou tronqué à droite.<br />Laissez vide ou entrez 0 pour désactiver cette fonction.',
	'HELP_DL_SHOW_FILE_HASH'		=> 'Affiche ou masque le hash du fichier dans les détails du téléchargement.',
	'HELP_DL_SHOW_FOOTER_LEGEND'	=> 'Active ou désactive la légende des icônes d\'état dans le pied de page des téléchargements.<br />Les icônes à côté des téléchargements ne sont pas modifiées par cette option.',
	'HELP_DL_SHOW_FOOTER_STAT'		=> 'Active ou désactive les lignes de statistiques dans le pied de page des téléchargements.<br />Les statistiques continueront toutefois à collecter des données si vous désactivez l\'affichage.',
	'HELP_DL_SHOW_REAL_FILETIME'	=> 'Affiche la véritable date/heure de la dernière modification du fichier dans les détails du téléchargement.<br />C\'est l\'horodatage le plus précis, même pour les fichiers uploadés via FTP.',
	'HELP_DL_SIMILAR_DL'			=> 'Affiche, dans la vue détaillée, des téléchargements similaires de la même catégorie.<br /><br />Remarque : sur de grandes bases de données, cette option peut augmenter le temps de chargement de la vue détaillée ; il peut être conseillé de la désactiver.',
	'HELP_DL_SIMILAR_DL_LIMIT'		=> 'Nombre de téléchargements similaires à afficher.',
	'HELP_DL_SORT_PREFORM'			=> 'L\'option "Preset" trie tous les téléchargements dans toutes les catégories pour tous les utilisateurs selon le tri défini dans l\'ACP.<br />Avec "User", chaque utilisateur peut choisir son tri et s\'il est fixe ou étendu par d\'autres critères.',
	'HELP_DL_STAT_PERM'				=> 'Sélectionnez ici à quel niveau d\'utilisateur la page des statistiques de téléchargement peut être consultée.<br />Par ex. si vous l\'activez pour les modérateurs des téléchargements, chaque administrateur et modérateur des téléchargements (PAS le modérateur de forum !) pourra voir cette page.<br />Notez que cette page peut générer une lourde charge, donc déconseillée pour un grand public sur de gros forums.',
	'HELP_DL_STATISTICS'			=> 'Active des statistiques détaillées sur les fichiers.<br />Notez que ces statistiques génèrent des requêtes supplémentaires et des jeux de données dans une table séparée.',
	'HELP_DL_STATS_PRUNE'			=> 'Entrez le nombre maximum de lignes de données que la statistique pour cette catégorie peut atteindre.<br />Chaque nouvelle ligne supprimera la plus ancienne.<br />Entrez 0 pour désactiver l\'élagage.',
	'HELP_DL_STOP_UPLOADS'			=> 'Vous pouvez activer/désactiver les uploads avec cette option.<br />Si vous désactivez, seuls les administrateurs pourront uploader de nouveaux fichiers.<br />Activez pour permettre aux utilisateurs d\'uploader selon les permissions de catégorie et de groupe.',

	'HELP_DL_THUMB'						=> 'Ce champ permet de téléverser une petite image (respectez la taille et le poids affichés sous ce champ) pour l\'afficher dans les détails du téléchargement.<br />Si une miniature existe déjà, vous pouvez en téléverser une nouvelle pour la remplacer.<br />Cochez "supprimer" pour supprimer la miniature existante.',
	'HELP_DL_THUMB_CAT'					=> 'Cette option active les miniatures pour les téléchargements de cette catégorie.<br />La taille des images est basée sur les paramètres de la configuration principale du MOD.',
	'HELP_DL_THUMB_MAX_DIM_X'			=> 'Cette valeur limite la largeur maximale des images uploadées pour les miniatures.<br />Les miniatures elles‑mêmes font au maximum 150 x 100 pixels et les images uploadées s\'ouvrent dans une popup en cliquant sur la miniature.<br /><br />Entrez 0 pour désactiver les miniatures (non recommandé si la taille des miniatures est définie).<br />Les miniatures existantes seront affichées tant que la taille maximale des miniatures n\'est pas réglée à 0.',
	'HELP_DL_THUMB_MAX_DIM_Y'			=> 'Cette valeur limite la hauteur maximale des images uploadées pour les miniatures.<br />Les miniatures elles‑mêmes font au maximum 150 x 100 pixels et les images uploadées s\'ouvrent dans une popup en cliquant sur la miniature.<br /><br />Entrez 0 pour désactiver les miniatures (non recommandé si la taille des miniatures est définie).<br />Les miniatures existantes seront affichées tant que la taille maximale des miniatures n\'est pas réglée à 0.',
	'HELP_DL_THUMB_MAX_SIZE'			=> 'Entrez 0 comme taille maximale pour désactiver les miniatures dans toutes les catégories.<br />Si vous autorisez les miniatures, indiquez la taille maximale des images uploadées à partir desquelles seront créées les miniatures.<br />Si vous désactivez les miniatures, vous ne verrez plus les miniatures existantes dans les détails.',
	'HELP_DL_TODO_LINK'					=> 'Active ou désactive le lien vers la todolist dans le pied de page des téléchargements. Les entrées et leur gestion ne sont pas affectées par ce changement.',
	'HELP_DL_USE_TODOLIST'				=> 'Active ou désactive la todolist.',
	'HELP_DL_TOPIC_DETAILS'				=> 'Affiche la description du téléchargement, le nom du fichier, la taille ou, pour les téléchargements externes, l\'URL dans le sujet du forum.<br />Le texte peut être placé avant ou après le texte saisi précédemment.<br />Si le sujet est créé via les catégories de téléchargements, l\'option de la configuration générale sera ignorée.',
	'HELP_DL_TOPIC_FORUM'				=> 'Le forum qui affichera les nouveaux sujets concernant les téléchargements.<br />Si vous sélectionnez "Category select", le sujet sera inséré dans le forum choisi dans les paramètres de catégorie.',
	'HELP_DL_TOPIC_FORUM_C'				=> 'Le forum qui affichera les nouveaux sujets concernant les téléchargements de cette catégorie.',
	'HELP_DL_TOPIC_POST_CATNAME'		=> 'Ajoute le nom de la catégorie dans le message du sujet généré pour les téléchargements. Le nom de la catégorie sera inséré après le titre du téléchargement.<br />Remarque : les sujets existants ne seront pas mis à jour tant que le téléchargement n\'est pas modifié.',
	'HELP_DL_TOPIC_TEXT'				=> 'Texte libre pour la création des sujets liés aux téléchargements. BBCodes, HTML et smileys ne sont pas autorisés ici ; le texte sert uniquement d\'introduction.',
	'HELP_DL_TOPIC_TITLE_CATNAME'		=> 'Ajoute le nom de la catégorie au titre du sujet généré pour les téléchargements. Le nom de la catégorie sera séparé du nom du téléchargement par un tiret (-).<br />Remarque : les sujets existants ne seront pas mis à jour tant que le téléchargement n\'est pas modifié.',
	'HELP_DL_TOPIC_USER'				=> 'Sélectionnez ici quel utilisateur sera l\'auteur des sujets de téléchargement.<br />Si l\'utilisateur courant doit être l\'auteur, choisissez "current user". L\'option "selected by category" permet de définir un utilisateur distinct pour chaque catégorie (par ID ou courant).<br /><br /><strong>Remarque :</strong><br />L\'ID utilisateur n\'est pas vérifié par le mod ; un ID invalide peut perturber les fonctions !',
	'HELP_DL_TRAFFIC'					=> 'Le trafic maximum qu\'un fichier pourra générer.<br />La valeur 0 désactive le contrôle du trafic.<br />Note : le trafic du fichier est mis à 0 même si le téléchargement est marqué comme externe.',
	'HELP_DL_TRAFFIC_OFF'				=> 'Désactive la gestion du trafic dans l\'espace téléchargement et désactive toutes les options liées au trafic.<br />En activant cette option, tous les textes relatifs au trafic de téléchargement sont masqués et les modifications de trafic lors d\'ajouts/suppressions de messages ne sont plus appliquées aux comptes utilisateurs.<br />Les affectations automatiques de trafic ne s\'effectueront plus si cette option est désactivée. Les modules d\'administration restent inchangés dans l\'ACP.',
	'HELP_DL_TRAFFICS_FOUNDER'			=> 'Lorsque la gestion du trafic est désactivée pour les fondateurs, ces utilisateurs peuvent télécharger et uploader sans limite malgré les options de trafic.<br />Ils ne recevront pas non plus de trafic automatique ni de points de trafic lors de la création de sujets ou messages même si ces options sont activées.',
	'HELP_DL_TRAFFICS_OVERALL'			=> 'Définit une limite pour le trafic global des utilisateurs enregistrés.<br />Le trafic global peut être activé pour tous les utilisateurs ou uniquement pour les groupes sélectionnés dans l\'option suivante.',
	'HELP_DL_TRAFFICS_OVERALL_GROUPS'	=> 'Cette option s\'appliquera aux groupes d\'utilisateurs sélectionnés et à leurs membres.',
	'HELP_DL_TRAFFICS_USERS'			=> 'Définit une limite de trafic par utilisateur pour les utilisateurs enregistrés.<br />Le trafic utilisateur peut être activé pour tous ou uniquement pour des groupes sélectionnés.<br />Si le trafic utilisateur est désactivé, les utilisateurs concernés pourront télécharger et uploader sans limite.',
	'HELP_DL_TRAFFICS_USERS_GROUPS'		=> 'Cette option s\'appliquera aux groupes d\'utilisateurs sélectionnés et à leurs membres.',
	'HELP_DL_TRAFFICS_GUESTS'			=> 'Active ou désactive le trafic global pour les invités.<br />Si désactivé, les invités pourront télécharger et uploader sans limite selon leurs permissions.<br />Cette option peut générer beaucoup de trafic et surcharger le serveur, il est donc déconseillé de la désactiver.',

	'HELP_DL_UCONF_LINK'			=> 'Affiche ou masque le lien vers la configuration utilisateur dans le pied de page des téléchargements. La configuration utilisateur elle‑même n\'est pas affectée par ce changement.',
	'HELP_DL_UPLOAD_FILE'			=> 'Le fichier à téléverser depuis votre ordinateur.<br />Assurez‑vous que la taille du fichier est inférieure à la limite affichée et que l\'extension n\'est pas dans la liste des extensions interdites.',
	'HELP_DL_UPLOAD_TRAFFIC_COUNT'	=> 'Si cette option est activée, les uploads diminueront également le trafic mensuel global.<br />Une fois le quota global atteint, aucun upload ne sera possible et les nouveaux téléchargements devront être ajoutés via FTP dans l\'ACP.',
	'HELP_DL_USE_EXT_BLACKLIST'		=> 'Si vous activez la blacklist, tous les types de fichiers listés seront bloqués pour les nouveaux téléchargements uploadés ou modifiés.',
	'HELP_DL_USE_HACKLIST'			=> 'Cette option active ou désactive la hacklist.<br />Si activée, vous pouvez ajouter des informations de hack lors de l\'ajout ou modification d\'un téléchargement pour l\'insérer dans la hacklist.<br />Si vous désactivez la hacklist, elle sera complètement masquée pour les utilisateurs, mais vous pouvez la réactiver à tout moment.<br />Note : les informations de hack dans les téléchargements seront perdues si vous éditez le fichier après la désactivation de la hacklist.',
	'HELP_DL_USER_TRAFFIC_ONCE'		=> 'Choisissez si le trafic utilisateur doit n\'être diminué que lors du premier téléchargement d\'un fichier.<br /><strong>Remarque :</strong><br />Cette option n\'affecte PAS l\'état du téléchargement lui‑même !',

	'HELP_DL_VISUAL_CONFIRMATION'	=> 'Activez cette option pour demander à l\'utilisateur de saisir un code de confirmation à 5 chiffres affiché afin d\'accéder au téléchargement.<br />Si le code est absent ou incorrect, le MOD affichera un message et interrompra le téléchargement.',

	'HELP_DOWNLOAD_PATH'			=> 'Le chemin relatif sous la racine de phpBB.<br />Après l\'installation, la valeur par défaut est "dl_mod/downloads/".<br />Faites attention à la casse sur Unix/Linux.<br />La barre oblique finale est importante, n\'en ajoutez pas au début.<br />Ce dossier et tous ses sous‑dossiers doivent être en CHMOD 777 pour que toutes les fonctions fonctionnent correctement.<br />Créez un ou plusieurs sous‑dossiers pour contenir les fichiers physiques (recommandé : un sous‑dossier par groupe logique de catégories).<br />Entrez le sous‑dossier comme chemin de catégorie sans inclure le dossier principal (voir l\'aide de la gestion des catégories).<br />Vous pouvez créer des sous‑dossiers via FTP ou la Toolbox (lien en haut à droite).',

	'HELP_NUMBER_RECENT_DL_ON_PORTAL'	=> 'Le nombre de derniers téléchargements affichés dans le bloc du portail.<br />Le bloc utilise la date de dernière modification pour cette liste ; il est donc possible qu\'un téléchargement plus ancien apparaisse en tête.',
));